default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: find_rooms_to_rent_development

test:
  <<: *default
  database: find_rooms_to_rent_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
